// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _05_Model.Data;

#nullable disable

namespace _05_Model.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250925150133_SeedEmployees")]
    partial class SeedEmployees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_05_Model.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "vana@example.com",
                            FullName = "Nguyen Van A",
                            Gender = "Male",
                            Phone = "0901234567",
                            Salary = 1200.50m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Email = "thib@example.com",
                            FullName = "Tran Thi B",
                            Gender = "Female",
                            Phone = "0912345678",
                            Salary = 1500.00m,
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 3,
                            Email = "vanc@example.com",
                            FullName = "Le Van C",
                            Gender = "Male",
                            Phone = "0987654321",
                            Salary = 1800.75m,
                            Status = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
