// <auto-generated />
using System;
using Day7Lab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day7Lab.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Day7Lab.Models.CtHoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("DonGiaMua")
                        .HasColumnType("float");

                    b.Property<int?>("HoaDonId")
                        .HasColumnType("int")
                        .HasColumnName("HoaDonID");

                    b.Property<int?>("SanPhamId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamID");

                    b.Property<int?>("SoLuongMua")
                        .HasColumnType("int");

                    b.Property<double?>("ThanhTien")
                        .HasColumnType("float");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK__CT_HOA_D__3214EC27CE99679B");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("CT_HOA_DON", (string)null);
                });

            modelBuilder.Entity("Day7Lab.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HoTenKhachHang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("MaKhaHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayHoaDon")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("datetime");

                    b.Property<double?>("TongTriGia")
                        .HasColumnType("float");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK__HOA_DON__3214EC27F2B2A746");

                    b.HasIndex("MaKhaHang");

                    b.HasIndex(new[] { "MaHoaDon" }, "UQ__HOA_DON__835ED13A71FAE05C")
                        .IsUnique()
                        .HasFilter("[MaHoaDon] IS NOT NULL");

                    b.ToTable("HOA_DON", (string)null);
                });

            modelBuilder.Entity("Day7Lab.Models.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HoTenKhachHang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaKhau")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("datetime");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK__KHACH_HA__3214EC2716DEDCD0");

                    b.HasIndex(new[] { "DienThoai" }, "UQ__KHACH_HA__1F031876FD7BA43B")
                        .IsUnique()
                        .HasFilter("[DienThoai] IS NOT NULL");

                    b.HasIndex(new[] { "MaKhachHang" }, "UQ__KHACH_HA__88D2F0E4F09C71EA")
                        .IsUnique()
                        .HasFilter("[MaKhachHang] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ__KHACH_HA__A9D1053400A0055E")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("KHACH_HANG", (string)null);
                });

            modelBuilder.Entity("Day7Lab.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaLoai")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenLoai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK__LOAI_SAN__3214EC27DDC9A147");

                    b.HasIndex(new[] { "MaLoai" }, "UQ__LOAI_SAN__730A5758114F4AF7")
                        .IsUnique()
                        .HasFilter("[MaLoai] IS NOT NULL");

                    b.ToTable("LOAI_SAN_PHAM", (string)null);
                });

            modelBuilder.Entity("Day7Lab.Models.QuanTri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TaiKhoan")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK__QUAN_TRI__3214EC27838A5F38");

                    b.HasIndex(new[] { "TaiKhoan" }, "UQ__QUAN_TRI__D5B8C7F01A99EE30")
                        .IsUnique()
                        .HasFilter("[TaiKhoan] IS NOT NULL");

                    b.ToTable("QUAN_TRI", (string)null);
                });

            modelBuilder.Entity("Day7Lab.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("MaSanPham")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK__SAN_PHAM__3214EC27160EACCA");

                    b.HasIndex("MaLoai");

                    b.HasIndex(new[] { "MaSanPham" }, "UQ__SAN_PHAM__FAC7442C235FEF00")
                        .IsUnique()
                        .HasFilter("[MaSanPham] IS NOT NULL");

                    b.ToTable("SAN_PHAM", (string)null);
                });

            modelBuilder.Entity("Day7Lab.Models.CtHoaDon", b =>
                {
                    b.HasOne("Day7Lab.Models.HoaDon", "HoaDon")
                        .WithMany("CtHoaDons")
                        .HasForeignKey("HoaDonId")
                        .HasConstraintName("FK__CT_HOA_DO__HoaDo__36B12243");

                    b.HasOne("Day7Lab.Models.SanPham", "SanPham")
                        .WithMany("CtHoaDons")
                        .HasForeignKey("SanPhamId")
                        .HasConstraintName("FK__CT_HOA_DO__SanPh__37A5467C");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Day7Lab.Models.HoaDon", b =>
                {
                    b.HasOne("Day7Lab.Models.KhachHang", "MaKhaHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKhaHang")
                        .HasConstraintName("FK__HOA_DON__MaKhaHa__33D4B598");

                    b.Navigation("MaKhaHangNavigation");
                });

            modelBuilder.Entity("Day7Lab.Models.SanPham", b =>
                {
                    b.HasOne("Day7Lab.Models.LoaiSanPham", "MaLoaiNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("FK__SAN_PHAM__MaLoai__2B3F6F97");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("Day7Lab.Models.HoaDon", b =>
                {
                    b.Navigation("CtHoaDons");
                });

            modelBuilder.Entity("Day7Lab.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Day7Lab.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Day7Lab.Models.SanPham", b =>
                {
                    b.Navigation("CtHoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
